### ISSUE TITLE
Server is not logging configuration errors

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#12]
If the admin defines a configuration that contains an invalid value (for example rpki.object.cleanup.grace.duration = BLABLABLA ), neither the server log nor the app log register the stack trace related to this configuration error.

It is necessary to provide logging for configuration errors.

**Comment by pcarana** [comment]
This seems a problem related with the tomcat default logging values. Currently the API manually sets the logging configuration file and it seems not have any effect (the logs aren't displayed neither on the catalina log nor the app log).

To keep it simple, now the app will use the expected behaviour (at least by tomcat) to find the customized logging properties files. If a `logging.properties` file exists at `WEB-INF/classes` then such file is used to configure the logging; otherwise the default tomcat logging configuration is used. See more at [Tomcat Docs - Using java.util.logging (default)](https://tomcat.apache.org/tomcat-8.5-doc/logging.html#Using_java.util.logging_(default)):

> JULI is enabled by default, and supports per classloader configuration, in addition to the regular global java.util.logging configuration. This means that logging can be configured at the following layers:
> 
> * Globally. That is usually done in the `${catalina.base}/conf/logging.properties` file. The file is specified by the `java.util.logging.config.file` System property which is set by the startup scripts. If it is not readable or is not configured, the default is to use the `${java.home}/lib/logging.properties` file in the JRE.
> * In the web application. The file will be `WEB-INF/classes/logging.properties`
>

**Comment by TheRedTrainer** [comment]
Verified. If there is any configuration property containing an invalid value, the server logs the corresponding stack trace on the log file configured previously in WEB-INF/classes/logging.properties .
